[package]
name = "balancer-arb-server"
version = "0.4.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
actix-files = "0.6"
actix-rt = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ethers = { version = "2.0", features = ["abigen", "ws"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
log = "0.4"
env_logger = "0.10"
dotenv = "0.15"
reqwest = { version = "0.11", features = ["json"] }
hex = "0.4"
bcrypt = "0.15"
uuid = { version = "1", features = ["v4"] }
sled = "0.34"
rand = "0.8"
futures-util = "0.3"
futures = "0.3.32"
